### ISSUE TITLE
Doesn't respect proxy settings

### ISSUE THREAD

**Issue by bmarwell** [linux-china/toolchains-maven-plugin#1]
Hi,

haven't looked through your code which technique of transferring files is being used. But proxy servers do not seem to be used at all. 
Can you confirm this?

**Comment by linux-china** [comment]
Fixed in version 4.3.0 

https://github.com/linux-china/toolchains-maven-plugin/blob/755cbcc13bc4b293dbb71feef306ad9e2efcd042/src/main/java/org/apache/maven/plugins/toolchain/FoojayService.java#L61
