### ISSUE TITLE
jdk vendor=ibm version=17 will download azul JDK

### ISSUE THREAD

**Issue by bmarwell** [linux-china/toolchains-maven-plugin#2]
https://github.com/bmarwell/jaxrs-test-showcase/pull/30

```
[INFO] --- toolchains-maven-plugin:4.2.0:toolchain (default) @ jaxrstesting-root ---
[INFO] Required toolchain: jdk [ vendor='ibm' version='17' ]
[INFO] Begin to install JDK 17
[INFO] Download zing22.07.0.0-3-jdk17.0.4-linux_x64.tar.gz from https://cdn.azul.com/zing-zvm/ZVM22.07.0.0/zing22.07.0.0-3-jdk17.0.4-linux_x64.tar.gz
[INFO] Extract zing22.07.0.0-3-jdk17.0.4-linux_x64.tar.gz
[INFO] JDK installed: /home/runner/.m2/jdks/zing22.07.0.0-3-jdk17.0.4-linux_x64
```

**Comment by bmarwell** [comment]
Actually, 'vendor' is a misnomer in this plugin. It should be 'dist' (the actual parameter which was called), a synonym to 'distribution'.

vendor=semeru will download dist=semeru. That works.

**Comment by HanSolo** [comment]
Just a little correction here, it should be distribution=semeru for example. distro also works but was from version 2.0. You should also use https://api.foojay.io/disco/v3.0 which is the latest version. 😁

**Comment by linux-china** [comment]
@HanSolo I have upgraded to V3.    @bmarwell  could you try version 4.3.0?  https://repo1.maven.org/maven2/org/mvnsearch/toolchains-maven-plugin/4.3.0/

**Comment by bmarwell** [comment]
+1 for the API call:
https://github.com/bmarwell/jaxrs-test-showcase/pull/50

Thanks!

:)
